# Generated by Django 5.0 on 2024-01-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lawyername', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('adr', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=100, null=True)),
                ('Phn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('domains', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('license_num', models.CharField(blank=True, max_length=10, null=True)),
                ('schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('edu_bg', models.CharField(blank=True, max_length=100, null=True)),
                ('Year_exp', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
