# Generated by Django 5.0 on 2024-01-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_groups_useraccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
    ]
