# Generated by Django 5.0 on 2024-01-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lawyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lawyer',
        ),
    ]
