# Generated by Django 5.0 on 2024-02-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
