# Generated by Django 5.0 on 2024-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_customuser_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
