# Generated by Django 5.0 on 2024-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lawyername', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('adr', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=100, null=True)),
                ('Phn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('domains', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('license_num', models.CharField(blank=True, max_length=10, null=True)),
                ('schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('edu_bg', models.CharField(blank=True, max_length=100, null=True)),
                ('Year_exp', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lawyers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('wilaya', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('phone_num', models.IntegerField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_lawyer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
