# Generated by Django 5.0 on 2024-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_lawyer',
            field=models.BooleanField(default=True),
        ),
    ]
