# Generated by Django 5.0 on 2024-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_is_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dateofbirth',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_num',
            field=models.IntegerField(default=1234567890),
        ),
    ]
