# Generated by Django 5.0 on 2024-02-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_active',
            new_name='is_added',
        ),
    ]
