# Generated by Django 5.0 on 2024-02-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
