# Generated by Django 5.0 on 2024-02-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_lawyers_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyers',
            name='is_active',
        ),
    ]
